# Generated by Django 4.2.4 on 2023-08-25 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('content_name', models.CharField(max_length=256)),
                ('content_info', models.TextField(blank=True)),
                ('content_date', models.DateField()),
                ('content_likes', models.IntegerField()),
                ('content_dislikes', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_info', models.TextField(blank=True)),
                ('comment_date', models.DateField()),
                ('comment_likes', models.IntegerField()),
                ('comment_dislikes', models.IntegerField()),
                ('comment_content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.content')),
            ],
        ),
    ]
